name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          path: "**/node_modules"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Rename build folder
        run: mv build rhinebar

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rhinebar
          path: rhinebar
